CREATE TABLE AMBULATORIO(
CODAMB INT PRIMARY KEY NOT NULL,
ANDAR INT,
CAPACIDADE INT
);

CREATE TABLE MEDICO(
CODM INT PRIMARY KEY NOT NULL,
NOME VARCHAR,
IDADE INT,
ESPECIALIDADE VARCHAR,
RG CHAR(30),
CIDADE VARCHAR,
CODAMB INT,
FOREIGN KEY (CODAMB) REFERENCES AMBULATORIO(CODAMB)
);

CREATE TABLE PACIENTE(
CODP INT PRIMARY KEY NOT NULL,
NOME VARCHAR,
CIDADE VARCHAR,
RG CHAR(30)
);

CREATE TABLE CONSULTA(
CODMEDICO INT,
CODP INT,
DATAS INT,
HORA INT,
PRIMARY KEY (CODMEDICO,CODP,DATAS),
FOREIGN KEY (CODMEDICO) REFERENCES MEDICO(CODM),
FOREIGN KEY (CODP) REFERENCES PACIENTE(CODP)
);

CREATE DATABASE LIVRO_RECEITAS