CREATE TABLE PRODUTO(
CODIGO_PRODUT INT PRIMARY KEY NOT NULL,
NOME_PRODUT VARCHAR,
CUSTO_UNIT INTEGER,
CATEGORIA CHAR(50),
DATA_VALI CHAR(20)
);

DROP TABLE PRODUTO,RECEITA,INGREDIENTE;

CREATE TABLE RECEITA(
CODIGO_REC INT PRIMARY KEY NOT NULL,
NOME_REC VARCHAR,
CUST_TOTAL INT
);

CREATE TABLE INGREDIENTE(
CODIGO_REC INT,
CODIGO_PRODUT INT,
QNTD INT,
PRIMARY KEY(CODIGO_REC,CODIGO_PRODUT),
FOREIGN KEY (CODIGO_REC) REFERENCES RECEITA(CODIGO_REC),
FOREIGN KEY (CODIGO_PRODUT) REFERENCES PRODUTO(CODIGO_PRODUT)
);


SELECT NOME_PRODUT,CUSTO_UNIT,DATA_VALI FROM PRODUTO WHERE CUSTO_UNIT< 8;
SELECT CODIGO_REC,NOME_REC,CUST_TOTAL FROM RECEITA WHERE CUST_TOTAL IS NOT NULL;
SELECT CODIGO_PRODUT,NOME_PRODUT WHERE